#!/bin/sh

/usr/bin/invoke_app -t shuttleit \
                         -C "start_jupyter -A -t -T @tool ShuttleIt.ipynb" \
                         -u anaconda-7 \
                         -w headless \
                         -r none